fullnameOverride: ""
replicaCount: 1
host: "meow.lemon"
namespace: default
image:
  repository: ducheved/cmconstructor
  pullPolicy: IfNotPresent
  tag: "under"
service:
  type: LoadBalancer
  port: 39531
  targetPort: 3000
ingressRoute:
  enabled: true
  tls:
    certResolver: default
  entryPoints:
    - websecure
  routes:
    - match: Host(`meow.lemon`)
      priority: 10
      services:
        - port: 80
          scheme: h2c
resources: {}