{{- $root := . -}}
{{- if .Values.ingressRoute.enabled -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "cmconstructor.fullname" $root }}
  namespace: {{ .Values.namespace }}
spec:
  entryPoints:
    {{- range .Values.ingressRoute.entryPoints }}
    - {{ . }}
    {{- end }}
  routes:
    {{- range .Values.ingressRoute.routes }}
    - kind: Rule
      match: {{ .match }}
      priority: {{ .priority }}
      services:
        {{- range .services }}
        - name: {{ include "cmconstructor.fullname" $root }}
          port: {{ .port }}
          {{- if .scheme }}
          scheme: {{ .scheme }}
          {{- end }}
        {{- end }}
    {{- end }}
  {{- if .Values.ingressRoute.tls }}
  tls:
    certResolver: {{ .Values.ingressRoute.tls.certResolver }}
  {{- end }}
{{- end }}