apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ default .Chart.Name .Values.fullnameOverride }}
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ default .Chart.Name .Values.fullnameOverride }}
            port:
              number: {{ .Values.service.port }}
  tls:
  - hosts:
    - {{ .Values.host }}
    secretName: {{ default .Chart.Name .Values.fullnameOverride }}-tls